alias ls="ls --color"
alias ll="ls -l --color"
alias la="ls -la --color"
alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd /"
alias minecraft="/opt/minecraft-launcher/minecraft-launcher"
alias rotepose="sshfs jeremy@64.68.203.171:/ rotepose/"
alias config="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias now="date +%s"
