alias ls="ls --color"
alias ll="ls -lh --color"
alias la="ls -lha --color"
alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd /"
alias minecraft="/opt/minecraft-launcher/minecraft-launcher"
alias config="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias now="date +%s"
alias do="ssh jeremy@67.205.181.29"
alias do_files="sshfs jeremy@67.205.181.29:/ thumb/"
